# Generated by Django 4.2.3 on 2023-07-19 02:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TBL_Usuario',
            fields=[
                ('id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='TBL_Video',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
                ('extension', models.CharField(max_length=5)),
                ('tamaño', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='TBL_Usuario_Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='avance3.tbl_usuario')),
                ('id_video', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='avance3.tbl_video')),
            ],
        ),
    ]
